<?php require_once('Layouts/cabecalho.phtml');?>

	<?php session_start(); $data = $_SESSION['data']; ?>
	
	<div class="panel">
	<div class="panel-heading">
		<table class="table table-striped">
			<tr>
			<td >Código do Filme: </td>
			<td><form method="get" action="../Controllers/porCodigo.php"><input class="form-control" type="number" name="codigo" id="codigo" min="11"></td>
			<td><button type="submit" class="btn btn-primary">Search</button></form></td>	
			</tr>
		</table>
	</div>
	<div class="panel-body">
<table class="table table-striped">
	<tr>
		<td style="font-weight:600;">Original Title </td>
		<td><input class="form-control" disabled type="text" value="<?=$data->original_title?>"></td>	
	</tr>
	<tr>
		<td style="font-weight:bold;">Genres </td>
		<td><input class="form-control" disabled type="text" value="<?php foreach ($data->genres as $genre) echo $genre->name . ' - ';?>"></td>			
	</tr>
	<tr>
		<td style="font-weight:bold;">Release Data </td>
		<td><input class="form-control" disabled type="text" value="<?=$data->release_date?>"></td>	
	</tr>
	<tr>
		<td style="font-weight:bold;">Production Contries </td>
		<td><input class="form-control" disabled type="text" value="<?php foreach ($data->production_countries as $countrie)echo $countrie->name . ' - ';?>"></td>	
	</tr>
	<tr>
		<td style="font-weight:bold;">Overview </td>
		<td><textarea class="form-control" cols="50" rows="5" disabled="true"><?=$data->overview?></textarea></td>
	</tr>
	<tr>
		<td style="font-weight:bold;">Vote </td>
		<td><input class="form-control" disabled type="text" value="<?=$data->vote_average?>"></td>	
	</tr>
</table>
<br>
<?php session_destroy(); echo '<pre>'; var_dump($data); ?>
</div>
</div>
</div>
</body>
</html>