<?php require_once('Layouts/cabecalho.phtml');?>

	<?php session_start(); ?>
	<div class="panel">
		<div class="panel-heading">
		<table class="table table-striped">
			<tr>
			<td >Pesquisar: </td>
			<td><form method="get" action="../Controllers/porAproximacao.php"><input class="form-control" type="text" name="busca" id="codigo" min="11"></td>
			<td><button type="submit" class="btn btn-primary">Search</button></form></td>	
			</tr>
		</table>
		<?php 
	
		if(isset($_SESSION['busca']))
		{
			require_once("../Controllers/porAproximacao.php");
			$paginator->showPaginator();
		}
		
		?>
		</div>
		<?php // ------------------------------ FIlmes ------------------------------------------- // ?>
		<div class="panel-body">
			<?php 
			if(!empty($var)) :
			foreach ($var->results as $value): ?>
			<table class="table table-striped">
				<tr>
				<td style="width:90%">
					<table class="table table-striped">
						<tr>
							<td>Título</td>
							<td style="font-weight:bold"><input class="form-control" disabled type="text" value="<?=$value->original_title?>"></td>	
						</tr>
						<tr>
							<td>Lançamento</td>
							<td><input class="form-control" disabled type="text" value="<?=$value->release_date?>"></td>	
						</tr>
						<tr>
							<td>Avaliação</td>
							<td><input class="form-control" disabled type="text" value="<?=$value->vote_average?>"></td>	
						</tr>
						<tr>
						<td>Popularidade</td>
							<td><input class="form-control" disabled type="text" value="<?=$value->popularity?>"></td>	
						</tr>
					</table>
				</td>
				<?php if(!empty($value->backdrop_path)): ?>
				<td>
					<img style="border:2px solid grey; border-radius:10px;" src="https://image.tmdb.org/t/p/w342/<?=$value->backdrop_path?>">
				</td>
				<?php else: ?>
				<td>
					<img style="border:2px solid grey; border-radius:10px;" src="../Images/no-image.png">
				</td>
				<?php endif; ?>
				</tr>
			</table>
			<?php endforeach; endif;?>
			<?php // ----------------------------------------------------------------------------------------- // ?>
		</div>

   </div>
 </div>
</body>
</html>
