<html>
<head>
</head>
	<title>ApiCon TheMovie</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	<?php require_once("../Controllers/porPopularidade.php");
	 isset($_GET['page']) ? $paginator = lista($_GET['page'],__FILE__) : $paginator = lista(1,__FILE__);
	 $data = $_SESSION['data'];
    ?>

</head>
<body>
<div class="container" style="margin-top:10px;">
<?php require_once('Layouts/menu.phtml');?>
	<div class="panel">
		<div class="panel-heading">

		<?php $paginator->showPaginator(); ?>

		<?php // ------------------------------------------- FIlmes ------------------------------------------- // ?>
		</div>
		<div class="panel-body">
			<?php foreach ($data as $key=>$value): ?>
			<table class="table table-striped">
				<tr>
					<td style="font-weight:bold"><input class="form-control" disabled type="text" value="<?=$value->original_title?>"></td>	
				</tr>
				<tr>
					<td><input class="form-control" disabled type="text" value="<?=$value->release_date?>"></td>	
				</tr>
				<tr>
					<td><input class="form-control" disabled type="text" value="<?=$value->overview?>"></td>	
				</tr>
				<tr>
					<td><input class="form-control" disabled type="text" value="<?=$value->vote_average?>"></td>	
				</tr>
				<tr>
					<td><input class="form-control" disabled type="text" value="<?=$value->popularity?>"></td>	
				</tr>
			</table>
			<?php endforeach; ?>

			<?php // ----------------------------------------------------------------------------------------- // ?> 

			<?php $paginator->showPaginator(); session_destroy(); ?>
		</div>
   </div>
</div>
</body>
</html>
