<html>
<head>
</head>
	<title>ApiCon TheMovie</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	<?php require_once("../Controllers/porPopularidade.php");

	 isset($_GET['page']) ? lista($_GET['page']) : lista(1);
	 
	 $atual_page = $_SESSION['atual_page'];
	 $total_pages = $_SESSION['total_pages'];
	 $results = $_SESSION['results'];

    ?>

</head>
<body>
<div class="container" style="margin-top:10px;">
<?php require_once('Layouts/menu.phtml');?>
	<div class="panel">
		<div class="panel-heading">
		<?php include("pagination.phtml"); ?>

		<?php // ------------------------------Resultados - FIlmes ------------------------------------------- // ?>
		</div>
		<div class="panel-body">
			<?php foreach ($results as $key=>$result): ?>
			<table class="table table-striped">
				<tr>
					<td style="font-weight:bold"><input class="form-control" disabled type="text" value="<?=$result->original_title?>"></td>	
				</tr>
				<tr>
					<td><input class="form-control" disabled type="text" value="<?=$result->release_date?>"></td>	
				</tr>
				<tr>
					<td><input class="form-control" disabled type="text" value="<?=$result->overview?>"></td>	
				</tr>
				<tr>
					<td><input class="form-control" disabled type="text" value="<?=$result->vote_average?>"></td>	
				</tr>
				<tr>
					<td><input class="form-control" disabled type="text" value="<?=$result->popularity?>"></td>	
				</tr>
			</table>
			<?php endforeach; ?>
			<?php // ----------------------------------------------------------------------------------------- // ?>
			<?php include("pagination.phtml"); session_destroy(); ?>
		</div>
   </div>
</div>
</body>
</html>
