<?php require_once('Layouts/cabecalho.phtml');?>

	<?php require_once("../Controllers/porNota.php");
	 isset($_GET['page']) ? $paginator = lista($_GET['page'],__FILE__) : $paginator = lista(1,__FILE__);
	 $data = $_SESSION['data'];
    ?>
	<div class="panel">
		<div class="panel-heading">

		<?php $paginator->showPaginator(); ?>

		<?php // ------------------------------------------- FIlmes ------------------------------------------- // ?>
		</div>
		<div class="panel-body">
			<?php foreach ($data as $key=>$value): ?>
			<table class="table table-striped">
				<tr>
				<td style="width:90%">
					<table class="table table-striped">
						<tr>
							<td>Título</td>
							<td style="font-weight:bold"><input class="form-control" disabled type="text" value="<?=$value->original_title?>"></td>	
						</tr>
						<tr>
							<td>Lançamento</td>
							<td><input class="form-control" disabled type="text" value="<?=$value->release_date?>"></td>	
						</tr>
						<tr>
							<td>Avaliação</td>
							<td><input class="form-control" disabled type="text" value="<?=$value->vote_average?>"></td>	
						</tr>
						<tr>
						<td>Popularidade</td>
							<td><input class="form-control" disabled type="text" value="<?=$value->popularity?>"></td>	
						</tr>
					</table>
				</td>
				<?php if(!empty($value->backdrop_path)): ?>
				<td>
					<img style="border:2px solid grey; border-radius:10px;" src="https://image.tmdb.org/t/p/w342/<?=$value->backdrop_path?>">
				</td>
				<?php else: ?>
				<td>
					<img style="border:2px solid grey; border-radius:10px;" src="../Images/no-image.png">
				</td>
				<?php endif; ?>

				</tr>
			</table>
			
			<?php endforeach; ?>

			<?php // ----------------------------------------------------------------------------------------- // ?> 

			<?php $paginator->showPaginator(); session_destroy(); ?>
		</div>
   </div>
</div>
</body>
</html>
